### ISSUE TITLE
Match roleAssignment -> scopes _only_ where explicit

### ISSUE THREAD

**Issue by ndowmon** [JupiterOne/graph-azure#146]
I have discussed with @aiwilliams that we don't want to generate  any placeholder entities for role assignment -> scope targets. If the entity is not found, we should not create a relationship.

The simple implementation creates a problem: what happens if we have a role assignment that points to a _known_ entity type (ex. `azure_keyvault_service`) that for some reason is not found with `jobState.findEntity(keyvaultId)`? We want to log that the entity was not found, so developers can see if there is something wrong with the implementation of `role_assignment->keyvault_service` relationships.

Simply logging any time an entity is _not_ found, however, will create noise for many, many entities that we're not ingesting yet. So we should first check if the resourceId matches a pattern we expect to ingest before looking for that entity. (`/subscriptions/<s-id>/resourceGroups/<rg-id>/providers/Microsoft.KeyVault/vaults/<v-id>`)

However, if we only create relationships when we _explicitly_ know the matching resource ID pattern, it requires that developers always add matching patterns for new resource entities. If an entity does exist in the job state, but there is not matcher, we should alert developers so they can add the new matching pattern and create relationships between `role_assignment` and the new entity type.

Since we want to be able to check if a target `scope` exists in the `jobState`, the step which generates `role-assignment->scope` relationships needs to run as late as possible in the dependency tree. This would require a change to the SDK.

**Comment by ndowmon** [comment]
Conversation with @austinkelleher gave me the good idea to simply put the `roleAssignment` to `scope` relationships step at the end of the `integrationSteps` array, so there's no need for any change to the SDK.

**Comment by aiwilliams** [comment]
Chatting with @ndowmon IRL, hoping this summarize some goals for integrations in general:

1. Do not fail ingestion when the set of data we handle can be completed; a subset we don't handle yet should not kill the step
2. Report to job event log a single event for the step which informs the user that a subset of the data is not currently handled
3. Report to integration developer through Sentry - not as an error, but a different kind of event - enough details from that event, avoiding PII/sensitive data, to discern how we might handle the subset; we'll need to ensure we have a process to review these kinds of events and get them into our work plans
4. Once the subset is handled, even in the case where we discern that we will never handle it because it isn't relevant, remove the logging of the event
5. When the set we finally intend to ingest cannot be ingested, presumably because we did not anticipate something, this SHOULD crash the step with an error; this should alert us and be addressed ASAP

Regarding 5, this has typically been API failures, where a complete set cannot be collected from the provider (401, 500 responses), or where our code references properties on `undefined` etc. That is, there is not necessarily a `throws` statement in the step. In cases where the step expects something - run types would be well used to validate the provider responses include the data we expect - a guard clause may `throws` to kill the step and provide details to the developer.

Regarding the implementation details for the Azure integration, I think we only really want to know, what is the type of resource that the permissions reference that we do not yet handle (known by looking for the id of the resource to match the patterns we map to _type values). The resource ID could be normalized so that we have a single entry for all ids of specific instances of a resource type. For example, this would be a single entry: `/subscriptions/<s-id>/resourceGroups/<rg-id>/providers/Microsoft.KeyVault/vaults/<v-id>`, using knowledge of how the ids are structured to remove things like the subscription id and vault id.

This could be a summary at the end of the step that processes assignments, and can be simply logged to CloudWatch, such as:

```ts
logger.info({
  scopesSkipped: ['/subscriptions/<s-id>/resourceGroups/<rg-id>/providers/Microsoft.KeyVault/vaults/<v-id>']
}, '[SKIP] Scopes in RoleAssignments do not match resources currently ingested');
```

**Comment by ndowmon** [comment]
Thanks for the write-up @aiwilliams.  I like the suggestion to report a single event for the step with a collection of the scopes that weren't identified.

**Comment by ndowmon** [comment]
Splitting this into two issues. This issue (#146) is to remove all mapped relationships from the `roleAssignment|allows|<scope>` and alert developers that an expected entity was not found in the job state.  #148 is to alert developers that an unexpected entity was found in the jobState and `dependsOn` and `_type` need to be added to the resource ID map.
